[build]
    publish = "dist"

[[plugins]]
    package = "netlify-plugin-submit-sitemap"

    [plugins.inputs]

    baseUrl = "http://matthewtingley.ca"

    sitemapPath = "/sitemap.xml"

    ignorePeriod = 0

    providers = [
        "google",
        "yandex"
    ]
    
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200